print('Welcome to the Band Name Generator.')
print('What\'s the name of the city you grew up in?')
city_name = input()
print('What\'s your prt\'s name?')
pets_name = input()
print(f'Your band name could be {city_name} {pets_name}')